[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_staking = "BYeWgc41pqNfXnjaP9iTfc8Rv5Wo6hRyspoT1g8HqU4r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/cubicus-pc/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
